# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2023 Datadog, Inc.
---
apiVersion: v1
kind: Namespace
metadata:
  name: gke-nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: simple-node
  namespace: gke-nodejs
  labels:
    name: simple-node-service
    app: simple-node
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30088
  selector:
    name: simple-node-pod
    app: simple-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-deploy
  namespace: gke-nodejs
  labels:
    name: simple-node-deploy
    app: simple-node
    tags.datadoghq.com/env: "gke-nodejs"
    tags.datadoghq.com/service: "gke-simple-nodejs"
    tags.datadoghq.com/version: "1.2.3"
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: simple-node-pod
      app: simple-node
  template:
    metadata:
      name: simple-node-pod
      labels:
        name: simple-node-pod
        app: simple-node
        tags.datadoghq.com/env: "gke-nodejs"
        tags.datadoghq.com/service: "gke-simple-nodejs"
        tags.datadoghq.com/version: "1.2.3"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/js-lib.version: "latest"
    spec:
      containers:
        - name: simple-node-pod
          image: kennethfoo24/simple-nodejs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_TRACE_DEBUG
              value: "true"
            - name: DD_TRACE_STARTUP_LOGS
              value: "true"
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
      restartPolicy: Always
